package gcplog

import (
	"log/slog"
	"os"
)

func ReplaceAttr(_ []string, a slog.Attr) slog.Attr {
	switch a.Key {
	case slog.LevelKey:
		return slog.Attr{
			Key:   "severity",
			Value: a.Value,
		}
	case slog.TimeKey:
		// Generated by GCP
		return slog.Attr{}
	case slog.MessageKey:
		return slog.Attr{
			Key:   "message",
			Value: a.Value,
		}
	default:
		return a
	}
}

func Setup() {
	logger := slog.New(
		slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{ReplaceAttr: ReplaceAttr}),
	)
	slog.SetDefault(logger)
}
